#=================================================
# For Linux with gfortran
#=================================================
F90 = gfortran
FCOPTS = -Ofast
LDOPTS = -Ofast

#======================
# INTEL MKL
#======================
LIBS =  -L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_gf_lp64 -lmkl_sequential -lmkl_core -lpthread -lm
